server:
  # 端口
  port: 8082
spring:
  # 邮件配置
  mail:
    # 邮件服务器地址
    host: smtp.163.com
    # 协议
    protocol: smtp
    # 编码格式
    default-encoding: UTF-8
    # 授权码（在邮箱开通时获取）
    password: MTCIQTGOREIFZAFX
    # 发送者邮箱地址
    username: cyt1542756558@163.com
    # 端口
    port: 25

  # rabbitmq 配置
  rabbitmq:
    # 用户名
    username: guest
    # 密码
    password: guest
    # 服务器地址
    host:
    # 端口
    port: 5672
